CREATE DATABASE ardcontroller;

USE ardcontroller;

CREATE TABLE ARD (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255),
    state TINYINT(1),
	last_modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
